# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: jhunlouiegonzales
tagline: Driving Innovation in Healthcare and Automotive Sector | Expert in Mobile and Software Development | Let's Push Boundaries!
email: junlouie.gonzales@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Driving Innovation in Healthcare and Automotive Sector | Expert in Mobile and Software Development | Let's Push Boundaries!
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/carsfast-logo.svg
thumbnail: https://my-website-thumbnail

twitter:
  username: jhunlouiegonzales
  card: summary

social:
  name: Jhun Louie Gonzales
  links:
    - https://www.facebook.com/jhunlouie.gonzales/
    - https://www.instagram.com/jhunlouiegonzales/
    - https://www.linkedin.com/in/jhun-louie-gonzales-66795712b/

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_picture_tag
  - jekyll-minifier
  - jekyll-sitemap

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Picture Tag
picture:
  source: "assets/imgs"
  output: "assets/imgs"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - netlify.toml
  - README.md
