name: Production Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Jekyll
        run: |
          sudo apt-get install -y libvips
          sudo gem install jekyll
          sudo gem install bundler --version 2.3.26
          
      - name: Build the artifact
        run: |
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build -d public --config \_config.yml,\_prod_env.yml --trace && cp ./robot.txt ./public/robot.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://www.jhunlouiegonzales.com --delete
